### ISSUE TITLE
Doesn't detect songs

### ISSUE THREAD

**Issue by ghost** [2d-archive/lavalink#10]
![image](https://user-images.githubusercontent.com/69215407/123861094-7126f180-d92f-11eb-8596-01bb5a73e3c3.png)

Hata: Error
Sonuç bulunamadı: no results found
Playlist: https://open.spotify.com/playlist/6LlLXu78D8CyyooJedrQoq

**Comment by viztea** [comment]
Lavalink doesn't support spotify, you'll have to resolve the spotify links yourself.
