### ISSUE TITLE
when I use the "setVolume" method of erela.js it gives me this error

### ISSUE THREAD

**Issue by nezts08** [2d-archive/lavalink#18]
when I configure the volume it says "The required library was not found" and I don't know why it gives me that error

bug image: https://ibb.co/GCfBx3j
specifications of my vps: https://ibb.co/NLtT18m

**Comment by viztea** [comment]
lavalink does not support arm architectures, use https://github.com/Cog-Creators/Lavalink-Jars/releases instead
